### ISSUE TITLE
FOV breaks transparent shaders

### ISSUE THREAD

**Issue by Isaiahfeldt** [MintLily/NotOptifine#4]
Not sure if this is even possible to fix, but certain transparent shaders break as soon as you increase the FOV by even a single unit. And by break I mean become invisible or not displayed. This may be a limitation of the shaders themselves but I'm not that technical when it comes to shaders.

### Demonstrations

- [AniPin](https://booth.pm/ja/items/2833141) - Uses a [Texture Overlay shader](https://kamishirolab.booth.pm/items/2303512): [Video demonstration](https://i.gyazo.com/da99b3258c6a10abc647ba9a39226c42.mp4)
- [VRCLens](https://booth.pm/ja/items/2283183) - Uses a unknown transparent shader for its focus dot tracking: [Video demonstration](https://i.gyazo.com/a9f1bd97b2ab257064626205cca2bc64.mp4)

**Comment by MintLily** [comment]
These avatar assets depend on using the default (unedited) VRChat camera settings. As the mod changes the FOV setting, it'll break the assets. TLDR; This is out of my control. I guess either avoid using the assets, or the mod. Or maybe while using the assets, use the default mod FOV setting of 65.
